CREATE OR REPLACE TABLE ANALYTICS.SALES_DATA AS
SELECT 
    ORDER_ID,
    DATE,
    STATUS,
    AMOUNT,
    CITY,
    CASE 
        WHEN AMOUNT > 500 THEN TRUE 
        ELSE FALSE 
    END AS IS_HIGH_VALUE
FROM STAGING.STG_SALES_DATA
WHERE DATE IS NOT NULL;